# Generated by Django 4.0.4 on 2022-05-16 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messageapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetb',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess', to=settings.AUTH_USER_MODEL),
        ),
    ]
