# Generated by Django 4.0.4 on 2022-05-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0002_alter_messagetb_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messagetb',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='messagetb',
            old_name='created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='messagetb',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
