# Generated by Django 4.0.4 on 2022-05-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageapp', '0003_alter_messagetb_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetb',
            name='messages',
            field=models.TextField(),
        ),
    ]
